### ISSUE TITLE
Request: Send block references as text

### ISSUE THREAD

**Issue by roamankiuser** [8bitgentleman/roam-depot-send-to-graph#3]
This is a great feature. Thank you!

One request: would it be possible to end block references as text rather than the block reference path ID?

I use block references liberally and the content of these blocks is not currently copied to the new graph.

Thanks again

**Comment by 8bitgentleman** [comment]
hmm I could resolve block references but probably not block embeds. Block embeds I could only resolve the top block which kind of defeats the point of the embed

**Comment by 8bitgentleman** [comment]
The biggest downside to that would be breaking blocks that reference other blocks in the tree. For example the ((child 2)) text would end up being duplicated in the below example

- parent ((child 2))
    - child 1
    - child 2

**Comment by roamankiuser** [comment]
> hmm I could resolve block references but probably not block embeds. Block embeds I could only resolve the top block which kind of defeats the point of the embed

Resolving block references would be a major win on its own :)

**Comment by roamankiuser** [comment]
> The biggest downside to that would be breaking blocks that reference other blocks in the tree. For example the ((child 2)) text would end up being duplicated in the below example
> 
> * parent ((child 2))
>   
>   * child 1
>   * child 2

I think hard coding the *text* across different blocks would be preferable to the current status, where the block reference presents as a random string of letters.

Worse:
- parent ((random string of letters with zero meaning))
- - child 1
- - child 2

Better:
- parent [hard coded child 2]
- - child 1
- - child 2

Many thanks for considering this

**Comment by 8bitgentleman** [comment]
This has been address in my latest commit which has been submitted for Roam's review. You can follow it [here](https://github.com/Roam-Research/roam-depot/pull/794).

Now block refs will all be resolved to pure text, even if they are internal
